
# 端口
server:
  port: 8080

spring:
  datasource:
    # mysql 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql 链接
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8
    # mysql username
    username: root
    # mysql password
    password: zl000000